from __future__ import annotations

import csv
import gzip
import json
import math
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Callable


ISD_LITE_OFFICIAL_PAGE = "https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database"
ISD_HISTORY_URL = "https://www.ncei.noaa.gov/pub/data/noaa/isd-history.csv"
ISD_LITE_BASE_URL = "https://www.ncei.noaa.gov/pub/data/noaa/isd-lite"

RAW_FIELDNAMES: tuple[str, ...] = (
    "station_id",
    "timestamp",
    "air_temperature_raw",
    "dew_point_temperature_raw",
    "sea_level_pressure_raw",
    "wind_direction_raw",
    "wind_speed_raw",
    "sky_cover_raw",
    "precipitation_1hr_raw",
    "precipitation_6hr_raw",
)

STANDARDIZED_FIELDNAMES: tuple[str, ...] = (
    "timestamp",
    "station_id",
    "latitude",
    "longitude",
    "air_temperature",
    "dew_point_temperature",
    "sea_level_pressure",
    "wind_speed",
    "wind_direction",
    "precipitation_1hr",
    "elevation",
    "station_age_years",
    "sensor_cost",
    "sensor_type",
    "sensor_group",
    "sensor_modality",
    "site_type",
    "maintenance_state",
    "source",
    "raw_station_name",
    "icao",
)


BytesFetcher = Callable[[str, int], bytes]


@dataclass(frozen=True)
class NoaaDownloadConfig:
    """Configuration for NOAA ISD-Lite downloads.

    Attributes:
        start_date: Inclusive start date.
        end_date: Inclusive end date.
        output_dir: Destination directory for generated files.
        country_code: ISO-like NOAA country code, for example `KS` for South Korea.
        station_ids: Optional explicit station ids formatted as `USAF-WBAN`.
        max_stations: Optional limit after filtering.
        raw_csv_path: Optional raw merged CSV path.
        standardized_csv_path: Optional framework-ready CSV path.
        metadata_csv_path: Optional station metadata CSV path.
        framework_config_path: Optional framework config path using the `isd_hourly` preset.
        overwrite: Whether to overwrite existing outputs.
        dry_run: Whether to only plan the download.
        timeout: HTTP timeout in seconds.
        max_retries: Retry budget per request.
    """

    start_date: date
    end_date: date
    output_dir: Path
    country_code: str = "KS"
    station_ids: tuple[str, ...] = ()
    max_stations: int | None = None
    raw_csv_path: Path | None = None
    standardized_csv_path: Path | None = None
    metadata_csv_path: Path | None = None
    framework_config_path: Path | None = None
    overwrite: bool = False
    dry_run: bool = False
    timeout: int = 60
    max_retries: int = 2


@dataclass(frozen=True)
class NoaaDownloadArtifacts:
    """Output artifacts generated by a NOAA ISD-Lite download."""

    output_dir: Path
    manifest_path: Path
    metadata_csv_path: Path
    raw_csv_path: Path | None
    standardized_csv_path: Path | None
    framework_config_path: Path | None
    station_count: int
    row_count: int
    dry_run: bool


def download_noaa_isd(
    config: NoaaDownloadConfig,
    *,
    fetcher: BytesFetcher | None = None,
) -> NoaaDownloadArtifacts:
    """Download NOAA ISD-Lite data and standardize it for the framework.

    Args:
        config: NOAA download configuration.
        fetcher: Optional HTTP fetch override used for testing.

    Returns:
        A dataclass describing generated files and row counts.
    """

    if config.end_date < config.start_date:
        raise ValueError("end_date must be on or after start_date.")
    if config.max_stations is not None and config.max_stations <= 0:
        raise ValueError("max_stations must be positive when provided.")

    fetch = fetcher or _default_fetcher
    output_dir = config.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_csv_path = config.raw_csv_path or output_dir / "noaa_isd_raw.csv"
    standardized_csv_path = config.standardized_csv_path or output_dir / "noaa_isd_framework.csv"
    metadata_csv_path = config.metadata_csv_path or output_dir / "isd_station_metadata.csv"
    manifest_path = output_dir / "noaa_download_manifest.json"
    framework_config_path = config.framework_config_path

    protected_paths = [manifest_path, metadata_csv_path]
    if not config.dry_run:
        protected_paths.extend([raw_csv_path, standardized_csv_path])
    if framework_config_path is not None:
        protected_paths.append(framework_config_path)
    for path in protected_paths:
        if path.exists() and not config.overwrite:
            raise FileExistsError(f"{path} already exists. Re-run with --overwrite to replace it.")

    metadata_rows = _fetch_station_metadata(fetch, timeout=config.timeout, max_retries=config.max_retries)
    selected_rows = _select_stations(
        metadata_rows,
        country_code=config.country_code,
        station_ids=config.station_ids,
        start_date=config.start_date,
        end_date=config.end_date,
        max_stations=config.max_stations,
    )
    _write_metadata_csv(metadata_csv_path, selected_rows)

    row_count = 0
    if not config.dry_run:
        raw_csv_path.parent.mkdir(parents=True, exist_ok=True)
        standardized_csv_path.parent.mkdir(parents=True, exist_ok=True)
        with raw_csv_path.open("w", encoding="utf-8", newline="") as raw_handle, standardized_csv_path.open(
            "w",
            encoding="utf-8",
            newline="",
        ) as standardized_handle:
            raw_writer = csv.DictWriter(raw_handle, fieldnames=list(RAW_FIELDNAMES))
            standardized_writer = csv.DictWriter(standardized_handle, fieldnames=list(STANDARDIZED_FIELDNAMES))
            raw_writer.writeheader()
            standardized_writer.writeheader()
            for metadata_row in selected_rows:
                for year in _iter_years(config.start_date, config.end_date):
                    url = _build_station_year_url(metadata_row["station_id"], year)
                    try:
                        payload = _fetch_with_retries(
                            fetch,
                            url=url,
                            timeout=config.timeout,
                            max_retries=config.max_retries,
                        )
                    except urllib.error.HTTPError as error:
                        if error.code == 404:
                            continue
                        raise
                    text = gzip.decompress(payload).decode("utf-8", errors="ignore")
                    for raw_row, standardized_row in _parse_station_payload(
                        text=text,
                        metadata_row=metadata_row,
                        start_date=config.start_date,
                        end_date=config.end_date,
                    ):
                        raw_writer.writerow(raw_row)
                        standardized_writer.writerow(standardized_row)
                        row_count += 1

        if framework_config_path is not None:
            from .framework import write_framework_template

            write_framework_template(
                framework_config_path,
                standardized_csv_path,
                preset="isd_hourly",
                force=True,
            )
    else:
        raw_csv_path = None
        standardized_csv_path = None
        if framework_config_path is not None:
            from .framework import write_framework_template

            write_framework_template(
                framework_config_path,
                output_dir / "noaa_isd_framework.csv",
                preset="isd_hourly",
                force=True,
            )

    manifest = {
        "source": "noaa_isd_lite",
        "country_code": config.country_code,
        "start_date": config.start_date.isoformat(),
        "end_date": config.end_date.isoformat(),
        "station_count": len(selected_rows),
        "row_count": row_count,
        "station_ids": [row["station_id"] for row in selected_rows],
        "metadata_csv_path": str(metadata_csv_path.resolve()),
        "raw_csv_path": None if raw_csv_path is None else str(raw_csv_path.resolve()),
        "standardized_csv_path": None if standardized_csv_path is None else str(standardized_csv_path.resolve()),
        "framework_config_path": None
        if framework_config_path is None
        else str(framework_config_path.resolve()),
        "official_sources": [ISD_LITE_OFFICIAL_PAGE, ISD_HISTORY_URL],
        "dry_run": config.dry_run,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    return NoaaDownloadArtifacts(
        output_dir=output_dir,
        manifest_path=manifest_path,
        metadata_csv_path=metadata_csv_path,
        raw_csv_path=raw_csv_path,
        standardized_csv_path=standardized_csv_path,
        framework_config_path=framework_config_path,
        station_count=len(selected_rows),
        row_count=row_count,
        dry_run=config.dry_run,
    )


def _default_fetcher(url: str, timeout: int) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "silence-aware-ids/1.0"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def _fetch_with_retries(
    fetcher: BytesFetcher,
    *,
    url: str,
    timeout: int,
    max_retries: int,
) -> bytes:
    attempts = 0
    while True:
        try:
            return fetcher(url, timeout)
        except Exception:
            if attempts >= max_retries:
                raise
            attempts += 1


def _fetch_station_metadata(fetcher: BytesFetcher, *, timeout: int, max_retries: int) -> list[dict[str, str]]:
    payload = _fetch_with_retries(fetcher, url=ISD_HISTORY_URL, timeout=timeout, max_retries=max_retries)
    text = payload.decode("utf-8", errors="ignore")
    rows: list[dict[str, str]] = []
    for row in csv.DictReader(text.splitlines()):
        station_id = f"{(row.get('USAF') or '').strip()}-{(row.get('WBAN') or '').strip()}"
        if station_id == "-":
            continue
        begin_text = (row.get("BEGIN") or "").strip()
        end_text = (row.get("END") or "").strip()
        rows.append(
            {
                "station_id": station_id,
                "usaf": (row.get("USAF") or "").strip(),
                "wban": (row.get("WBAN") or "").strip(),
                "station_name": (row.get("STATION NAME") or "").strip(),
                "country_code": (row.get("CTRY") or "").strip(),
                "state": (row.get("STATE") or "").strip(),
                "icao": (row.get("ICAO") or "").strip(),
                "latitude": _clean_signed_text(row.get("LAT")),
                "longitude": _clean_signed_text(row.get("LON")),
                "elevation": _clean_numeric_text(row.get("ELEV(M)")),
                "begin": begin_text,
                "end": end_text,
            }
        )
    return rows


def _select_stations(
    metadata_rows: list[dict[str, str]],
    *,
    country_code: str,
    station_ids: tuple[str, ...],
    start_date: date,
    end_date: date,
    max_stations: int | None,
) -> list[dict[str, str]]:
    explicit_ids = {value.strip() for value in station_ids if value.strip()}
    start_int = int(start_date.strftime("%Y%m%d"))
    end_int = int(end_date.strftime("%Y%m%d"))
    selected: list[dict[str, str]] = []
    for row in metadata_rows:
        if explicit_ids and row["station_id"] not in explicit_ids:
            continue
        if not explicit_ids and row["country_code"] != country_code:
            continue
        begin_text = (row.get("begin") or "")[:8]
        end_text = (row.get("end") or "")[:8]
        try:
            begin_int = int(begin_text)
            finish_int = int(end_text)
        except ValueError:
            continue
        if begin_int > end_int or finish_int < start_int:
            continue
        selected.append(row)
    selected.sort(key=lambda item: item["station_id"])
    if max_stations is not None:
        selected = selected[:max_stations]
    if not selected:
        raise ValueError("No NOAA ISD stations matched the requested filters.")
    return selected


def _write_metadata_csv(metadata_csv_path: Path, metadata_rows: list[dict[str, str]]) -> None:
    with metadata_csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "station_id",
                "usaf",
                "wban",
                "station_name",
                "country_code",
                "icao",
                "latitude",
                "longitude",
                "elevation",
                "begin",
                "end",
            ],
        )
        writer.writeheader()
        for row in metadata_rows:
            writer.writerow(
                {
                    "station_id": row["station_id"],
                    "usaf": row["usaf"],
                    "wban": row["wban"],
                    "station_name": row["station_name"],
                    "country_code": row["country_code"],
                    "icao": row["icao"],
                    "latitude": row["latitude"],
                    "longitude": row["longitude"],
                    "elevation": row["elevation"],
                    "begin": row["begin"],
                    "end": row["end"],
                }
            )


def _iter_years(start_date: date, end_date: date) -> list[int]:
    return list(range(start_date.year, end_date.year + 1))


def _build_station_year_url(station_id: str, year: int) -> str:
    return f"{ISD_LITE_BASE_URL}/{year}/{station_id}-{year}.gz"


def _parse_station_payload(
    *,
    text: str,
    metadata_row: dict[str, str],
    start_date: date,
    end_date: date,
) -> list[tuple[dict[str, str], dict[str, str]]]:
    results: list[tuple[dict[str, str], dict[str, str]]] = []
    start_ts = datetime.combine(start_date, datetime.min.time())
    end_ts = datetime.combine(end_date, datetime.max.time()).replace(microsecond=0)
    station_age_years = _station_age_years(metadata_row["begin"], start_date)
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 12:
            continue
        try:
            stamp = datetime(
                year=int(parts[0]),
                month=int(parts[1]),
                day=int(parts[2]),
                hour=int(parts[3]),
            )
        except ValueError:
            continue
        if stamp < start_ts or stamp > end_ts:
            continue
        raw_row = {
            "station_id": metadata_row["station_id"],
            "timestamp": stamp.isoformat(timespec="minutes"),
            "air_temperature_raw": parts[4],
            "dew_point_temperature_raw": parts[5],
            "sea_level_pressure_raw": parts[6],
            "wind_direction_raw": parts[7],
            "wind_speed_raw": parts[8],
            "sky_cover_raw": parts[9],
            "precipitation_1hr_raw": parts[10],
            "precipitation_6hr_raw": parts[11],
        }
        standardized_row = {
            "timestamp": stamp.isoformat(timespec="minutes"),
            "station_id": metadata_row["station_id"],
            "latitude": metadata_row["latitude"],
            "longitude": metadata_row["longitude"],
            "air_temperature": _scale_or_blank(parts[4], 10.0),
            "dew_point_temperature": _scale_or_blank(parts[5], 10.0),
            "sea_level_pressure": _scale_or_blank(parts[6], 10.0),
            "wind_speed": _scale_or_blank(parts[8], 10.0),
            "wind_direction": _blank_if_missing(parts[7]),
            "precipitation_1hr": _scale_or_blank(parts[10], 10.0),
            "elevation": metadata_row["elevation"],
            "station_age_years": station_age_years,
            "sensor_cost": "1.0",
            "sensor_type": "isd_station",
            "sensor_group": "surface",
            "sensor_modality": "synoptic_surface",
            "site_type": "airport" if metadata_row["icao"] else "surface_station",
            "maintenance_state": "",
            "source": "noaa_isd_lite",
            "raw_station_name": metadata_row["station_name"],
            "icao": metadata_row["icao"],
        }
        results.append((raw_row, standardized_row))
    return results


def _station_age_years(begin_text: str, start_date: date) -> str:
    try:
        begin_date = datetime.strptime(begin_text[:8], "%Y%m%d").date()
    except ValueError:
        return ""
    delta_days = max((start_date - begin_date).days, 0)
    years = delta_days / 365.25
    return f"{years:.1f}"


def _scale_or_blank(value: str, scale: float) -> str:
    cleaned = _blank_if_missing(value)
    if cleaned == "":
        return ""
    return f"{int(cleaned) / scale:.1f}"


def _blank_if_missing(value: str | None) -> str:
    if value is None:
        return ""
    stripped = value.strip()
    if stripped in {"", "-9999", "-999", "-99"}:
        return ""
    return stripped


def _clean_signed_text(value: str | None) -> str:
    stripped = (value or "").strip()
    if not stripped:
        return ""
    try:
        return f"{float(stripped):.3f}"
    except ValueError:
        return ""


def _clean_numeric_text(value: str | None) -> str:
    stripped = (value or "").strip()
    if not stripped:
        return ""
    try:
        parsed = float(stripped)
    except ValueError:
        return ""
    if math.isnan(parsed):
        return ""
    return f"{parsed:.1f}"
